@startmindmap
+ Backtesting
++ COMMON BACKTESTING PLATFORMS
++ FINDING AND USING HISTORICAL DATABASES
++ PERFORMANCE MEASUREMENT
++ COMMON BACKTESTING PITFALLS TO AVOID
++ TRANSACTION COSTS
++ STRATEGY REFINEMENT
@endmindmap